/**
 * Claude Code SDK integration.
 *
 * Spawns `claude` as a child process with --output-format stream-json
 * and --input-format stream-json for persistent bidirectional communication.
 *
 * Supports multiple concurrent conversations, each with its own Claude process.
 * Conversations are keyed by conversationId (a UUID generated by the web client).
 * When no conversationId is provided (backward compat), uses 'default' as the key.
 *
 * Lifecycle:
 *   1.  Web user sends first message → startQuery() spawns Claude process
 *   2.  Each user message is enqueued into the inputStream
 *   3.  processOutput() iterates Claude stdout, forwarding messages via sendFn
 *   4.  On 'result' message → turn is complete, process stays alive for next turn
 *   5.  On abort / process exit → cleanup
 */

import { spawn, execSync, type ChildProcess } from 'child_process';
import { createInterface } from 'readline';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { Stream } from './stream.js';
import {
  resolveClaudeCommand,
  getCleanEnv,
  streamToStdin,
} from './sdk.js';
import { CONFIG_DIR } from './config.js';
import { saveSessionMetadata } from './session-metadata.js';
import { readConversationContext } from './history.js';
import {
  buildControlResponse,
  handleResultMessage,
  handleAssistantMessage,
  isTaskNotification,
  handleUserMessage,
} from './claude-message-helpers.js';

export {
  buildControlResponse,
  handleResultMessage,
  handleAssistantMessage,
  isTaskNotification,
  handleUserMessage,
} from './claude-message-helpers.js';

// ── Types ──────────────────────────────────────────────────────────────────

export interface ClaudeMessage {
  type: string;
  subtype?: string;
  [key: string]: unknown;
}

export interface ChatFile {
  name: string;
  mimeType: string;
  data: string; // base64
}

export interface ConversationState {
  child: ChildProcess | null;
  inputStream: Stream<ClaudeMessage> | null;
  abortController: AbortController | null;
  claudeSessionId: string | null;
  workDir: string;
  turnActive: boolean;
  turnResultReceived: boolean;
  // Multi-session fields
  conversationId: string;
  lastClaudeSessionId: string | null;
  isCompacting: boolean;
  createdAt: number;
  // Plan mode: when true, agent uses --permission-mode plan (Claude natively enforces read-only)
  planMode: boolean;
  // Brain mode: when true, session metadata is persisted with brainMode flag
  brainMode: boolean;
}

export type SendFn = (msg: Record<string, unknown>) => void;

// ── Control request types ──────────────────────────────────────────────────

interface ControlRequest {
  type: 'control_request';
  request_id: string;
  request: {
    subtype: string;
    tool_name?: string;
    input?: Record<string, unknown>;
  };
}

interface PendingControlRequest {
  request: ControlRequest;
  child: ChildProcess;
  conversationId: string;
}

// ── Constants ─────────────────────────────────────────────────────────────

const DEFAULT_CONVERSATION_ID = 'default';
export const MAX_CHAT_CONVERSATIONS = 15;
export const MAX_LOOP_CONVERSATIONS = 3;

/** @deprecated Use MAX_CHAT_CONVERSATIONS instead. Kept for backward compat. */
export const MAX_CONVERSATIONS = MAX_CHAT_CONVERSATIONS;

function isLoopConversation(conversationId: string): boolean {
  return conversationId.startsWith('loop-');
}

function getConversationCount(type: 'chat' | 'loop'): number {
  let count = 0;
  for (const [id] of conversations) {
    if (type === 'loop' && isLoopConversation(id)) count++;
    if (type === 'chat' && !isLoopConversation(id)) count++;
  }
  return count;
}

// ── Helpers ──────────────────────────────────────────────────────────────
// buildControlResponse moved to claude-message-helpers.ts

// ── Module state ───────────────────────────────────────────────────────────

const conversations = new Map<string, ConversationState>();
let sendFn: SendFn = () => {};
const pendingControlRequests = new Map<string, PendingControlRequest>();

// ── Output observer chain ──────────────────────────────────────────────────
// Callbacks invoked for every parsed JSON line from Claude stdout.
// Receives (conversationId, rawMessage). If any observer returns true, the
// message is suppressed from normal forwarding to the web client.
// Multiple observers can be registered (e.g., team + loop).

type OutputObserverFn = (conversationId: string, msg: ClaudeMessage) => boolean | void;
const outputObservers: OutputObserverFn[] = [];

export function addOutputObserver(fn: OutputObserverFn): void {
  outputObservers.push(fn);
}

export function removeOutputObserver(fn: OutputObserverFn): void {
  const idx = outputObservers.indexOf(fn);
  if (idx >= 0) outputObservers.splice(idx, 1);
}

/** @deprecated Use addOutputObserver() instead. Kept for backward compat (team.ts). */
export function setOutputObserver(fn: OutputObserverFn): void {
  addOutputObserver(fn);
}

/** @deprecated Use removeOutputObserver() instead. Clears ALL observers. */
export function clearOutputObserver(): void {
  outputObservers.length = 0;
}

// ── Close observer chain ──────────────────────────────────────────────────
// Callbacks invoked when a Claude process exits. Receives
// (conversationId, exitCode, resultReceived). Allows the team module to
// detect Lead crashes and the scheduler to detect Loop process exits.

type CloseObserverFn = (conversationId: string, exitCode: number | null, resultReceived: boolean) => void;
const closeObservers: CloseObserverFn[] = [];

export function addCloseObserver(fn: CloseObserverFn): void {
  closeObservers.push(fn);
}

export function removeCloseObserver(fn: CloseObserverFn): void {
  const idx = closeObservers.indexOf(fn);
  if (idx >= 0) closeObservers.splice(idx, 1);
}

/** @deprecated Use addCloseObserver() instead. Kept for backward compat (team.ts). */
export function setCloseObserver(fn: CloseObserverFn): void {
  addCloseObserver(fn);
}

/** @deprecated Use removeCloseObserver() instead. Clears ALL close observers. */
export function clearCloseObserver(): void {
  closeObservers.length = 0;
}

export function setSendFn(fn: SendFn): void {
  sendFn = fn;
}

/**
 * Get a conversation by its conversationId.
 * If no conversationId is provided, returns the 'default' conversation (backward compat).
 */
export function getConversation(conversationId?: string): ConversationState | null {
  return conversations.get(conversationId || DEFAULT_CONVERSATION_ID) || null;
}

/** Get all active conversations. */
export function getConversations(): Map<string, ConversationState> {
  return conversations;
}

/**
 * Evict any idle conversation that holds the given claudeSessionId.
 * Returns true if a busy (turnActive) conversation blocked the eviction.
 */
export function evictByClaudeSessionId(claudeSessionId: string): boolean {
  for (const [convId, conv] of conversations) {
    if (conv.claudeSessionId === claudeSessionId || conv.lastClaudeSessionId === claudeSessionId) {
      if (conv.turnActive) return true; // busy — caller should block
      cleanupConversation(convId);
    }
  }
  return false;
}

/**
 * Rebind a running conversation to a new conversationId.
 * Finds the conversation by claudeSessionId and remaps its key in the Map.
 * Used when the web client reconnects (page refresh) with a new conversationId.
 */
export function rebindConversation(claudeSessionId: string, newConvId: string): boolean {
  if (conversations.has(newConvId)) {
    return false;
  }
  for (const [oldConvId, conv] of conversations) {
    if ((conv.claudeSessionId === claudeSessionId || conv.lastClaudeSessionId === claudeSessionId)
        && oldConvId !== newConvId) {
      conversations.delete(oldConvId);
      conv.conversationId = newConvId;
      conversations.set(newConvId, conv);
      // Update pending control requests that reference the old conversationId
      for (const pending of pendingControlRequests.values()) {
        if (pending.conversationId === oldConvId) {
          pending.conversationId = newConvId;
        }
      }
      console.log(`[Claude] Rebound conversation ${oldConvId.slice(0, 8)} → ${newConvId.slice(0, 8)} (session ${claudeSessionId.slice(0, 8)})`);
      return true;
    }
  }
  return false;
}

/** Whether context compaction is currently in progress for a conversation. */
export function getIsCompacting(conversationId?: string): boolean {
  const conv = conversations.get(conversationId || DEFAULT_CONVERSATION_ID);
  return conv?.isCompacting ?? false;
}

/**
 * Clear the saved session ID for a conversation.
 * If no conversationId is provided, clears all (backward compat).
 */
export function clearSessionId(conversationId?: string): void {
  if (conversationId) {
    const conv = conversations.get(conversationId);
    if (conv) {
      conv.lastClaudeSessionId = null;
    }
  } else {
    for (const conv of conversations.values()) {
      conv.lastClaudeSessionId = null;
    }
  }
}

// ── Public API ─────────────────────────────────────────────────────────────

/** Options for handleChat() */
export interface HandleChatOptions {
  resumeSessionId?: string;
  brainMode?: boolean;
}

/**
 * Handle a chat message from the web client.
 * Lazily starts the Claude process on the first message.
 * If resumeSessionId is provided, resumes that Claude session.
 */
export function handleChat(
  conversationId: string | undefined,
  prompt: string,
  workDir: string,
  options?: HandleChatOptions,
  files?: ChatFile[],
): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const existing = conversations.get(convId);

  if (!existing || !existing.inputStream) {
    // If the process exited but we still know the session ID, resume it
    const sessionToResume = options?.resumeSessionId || existing?.claudeSessionId || existing?.lastClaudeSessionId || undefined;
    startQuery(convId, workDir, sessionToResume, options?.brainMode);
  }

  const state = conversations.get(convId)!;
  state.turnActive = true;
  state.turnResultReceived = false;
  if (options?.brainMode) state.brainMode = true;

  console.log(`[Claude:${convId.slice(0, 8)}] Sending: ${prompt.substring(0, 100)}${prompt.length > 100 ? '...' : ''}`);

  if (files && files.length > 0) {
    const content = processFilesForClaude(files, workDir, prompt);
    state.inputStream!.enqueue({
      type: 'user',
      message: { role: 'user', content },
    });
  } else {
    state.inputStream!.enqueue({
      type: 'user',
      message: { role: 'user', content: prompt },
    });
  }
}

/**
 * Abort a specific conversation's Claude process.
 * If no conversationId, aborts the 'default' conversation (backward compat).
 */
export function abort(conversationId?: string): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  if (!conv) return;

  if (conv.abortController) {
    conv.abortController.abort();
  }
  cleanupConversation(convId);
}

/**
 * Abort all conversations (used on agent shutdown).
 */
export function abortAll(): void {
  for (const convId of [...conversations.keys()]) {
    abort(convId);
  }
}

/**
 * Cancel the current execution for a conversation (user pressed stop button).
 * Kills the process and notifies the web client.
 */
export function cancelExecution(conversationId?: string): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  if (!conv) return;

  console.log(`[Claude:${convId.slice(0, 8)}] Cancelling execution`);
  conv.turnActive = false;

  if (conv.abortController) {
    conv.abortController.abort();
  }
  cleanupConversation(convId);

  sendFn({ type: 'execution_cancelled', conversationId: convId });
}

/**
 * Handle the user's answer to an AskUserQuestion control request.
 * Writes a control_response back to Claude's stdin.
 */
export function handleUserAnswer(requestId: string, answers: Record<string, unknown>): void {
  const pending = pendingControlRequests.get(requestId);
  if (!pending) {
    console.warn(`[Claude] No pending control request for requestId: ${requestId}`);
    return;
  }

  pendingControlRequests.delete(requestId);
  console.log(`[Claude] Answering AskUserQuestion ${requestId}`);

  const response = buildControlResponse(pending.request.request_id, {
    questions: pending.request.request.input?.questions || [],
    answers,
  });

  if (pending.child.stdin && !pending.child.stdin.destroyed) {
    pending.child.stdin.write(JSON.stringify(response) + '\n');
  }
}

/**
 * Handle a /btw side question. Spawns a lightweight, ephemeral Claude query
 * with inline conversation context (stripped-down dialogue) instead of
 * --resume. Streams btw_answer deltas back to the web client.
 */
export async function handleBtwQuestion(
  question: string,
  conversationId: string | undefined,
  workDir: string,
  send: (msg: Record<string, unknown>) => void,
  fallbackClaudeSessionId?: string,
): Promise<void> {
  // 1. Find the session ID for context from the conversations map
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  const sessionId = conv?.claudeSessionId || conv?.lastClaudeSessionId || fallbackClaudeSessionId || null;

  const effectiveWorkDir = conv?.workDir || workDir;

  // 2. Build inline context from the session JSONL
  let composedPrompt: string;
  if (sessionId) {
    let context: string | null = null;
    try {
      context = readConversationContext(effectiveWorkDir, sessionId);
    } catch (err) {
      console.warn(`[Claude:btw] Failed to read context: ${(err as Error).message}`);
    }

    if (context) {
      composedPrompt = `This is a side question from the user — a quick, read-only query that should not affect the current task.

Rules:
- Answer concisely based on the conversation context and your knowledge
- Do NOT call any tools (no file reads, no bash commands, no edits)
- Do NOT produce any tool_use blocks
- Do NOT continue or modify the main task

<conversation-context>
${context}
</conversation-context>

Side question: ${question}`;
    } else {
      composedPrompt = `Answer this question concisely. No tool calls, no file operations — text answer only.

Question: ${question}`;
    }
  } else {
    composedPrompt = `Answer this question concisely. No tool calls, no file operations — text answer only.

Question: ${question}`;
  }

  // 3. Build args — prompt is piped via stdin to avoid OS arg-length limits (ENAMETOOLONG)
  const args = [
    '-p', '-',
    '--no-session-persistence',
    '--output-format', 'stream-json',
    '--verbose',
  ];

  const { command, prefixArgs, spawnOpts } = conv?.brainMode
    ? { command: 'brain', prefixArgs: [] as string[], spawnOpts: { shell: true } }
    : resolveClaudeCommand();
  const env = getCleanEnv();

  let child: ChildProcess;
  try {
    child = spawn(command, [...prefixArgs, ...args], {
      cwd: effectiveWorkDir,
      stdio: ['pipe', 'pipe', 'pipe'],
      env,
      ...spawnOpts,
      windowsHide: true,
    });
  } catch (err) {
    send({ type: 'btw_answer', delta: `Failed to spawn Claude: ${(err as Error).message}`, done: true });
    return;
  }

  // Pipe the composed prompt via stdin, then close — avoids OS arg-length limits
  if (child.stdin) {
    child.stdin.write(composedPrompt);
    child.stdin.end();
  }

  // 4. Parse streaming JSON output and forward text deltas
  const rl = createInterface({ input: child.stdout! });
  let lastSentText = '';
  let sentAnyDelta = false;

  const stderrBuf: string[] = [];
  child.stderr?.on('data', (data: Buffer) => {
    stderrBuf.push(data.toString());
  });

  try {
    for await (const line of rl) {
      if (!line.trim()) continue;
      let msg: ClaudeMessage;
      try {
        msg = JSON.parse(line);
      } catch {
        continue;
      }

      // Extract text deltas from assistant messages
      if (msg.type === 'assistant' && msg.message) {
        const message = msg.message as { content?: Array<Record<string, unknown>> };
        const content = message.content;
        if (!Array.isArray(content)) continue;

        const fullText = content
          .filter((b) => b.type === 'text')
          .map((b) => (b.text as string) || '')
          .join('');

        if (fullText.length > lastSentText.length) {
          const delta = fullText.slice(lastSentText.length);
          lastSentText = fullText;
          sentAnyDelta = true;
          send({ type: 'btw_answer', delta, done: false });
        }
      }

      // On result, mark done
      if (msg.type === 'result') {
        // If result contains text we haven't sent yet
        if (typeof msg.result === 'string' && msg.result.length > lastSentText.length) {
          const delta = msg.result.slice(lastSentText.length);
          send({ type: 'btw_answer', delta, done: true });
        } else {
          send({ type: 'btw_answer', delta: '', done: true });
        }
        rl.close();
        return;
      }
    }
  } catch (err) {
    const error = err as Error;
    if (error.name !== 'AbortError') {
      console.error(`[Claude:btw] Stream error: ${error.message}`);
    }
  } finally {
    rl.close();
  }

  // If we reach here without sending done (process exited without result message)
  if (!sentAnyDelta) {
    const stderrText = stderrBuf.join('').trim();
    const errorMsg = stderrText || 'Side question failed — no response received.';
    send({ type: 'btw_answer', delta: errorMsg, done: true });
  } else {
    send({ type: 'btw_answer', delta: '', done: true });
  }
}

// ── Internal ───────────────────────────────────────────────────────────────

/**
 * Set the permission mode for a conversation.
 * Kills the current Claude process (if any) and stores the new mode so the
 * next `handleChat()` call spawns Claude with the correct `--permission-mode`.
 */
export function setPermissionMode(
  conversationId: string | undefined,
  mode: 'bypassPermissions' | 'plan',
  claudeSessionId?: string,
): 'injected' | 'immediate' {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const existing = conversations.get(convId);
  const enteringPlan = mode === 'plan';

  if (existing) {
    // If the process is alive and idle, inject a user message to make Claude
    // call EnterPlanMode / ExitPlanMode natively — this records the mode switch
    // in the JSONL history so Claude stays aware of the current mode across resumes.
    if (existing.child && !existing.child.killed && existing.inputStream && !existing.turnActive) {
      existing.planMode = enteringPlan;
      const instruction = enteringPlan
        ? 'Enter plan mode now.'
        : 'Exit plan mode now.';
      existing.turnActive = true;
      existing.turnResultReceived = false;
      existing.inputStream.enqueue({
        type: 'user',
        message: { role: 'user', content: instruction },
      });
      console.log(`[Claude:${convId.slice(0, 8)}] Injected ${enteringPlan ? 'EnterPlanMode' : 'ExitPlanMode'} instruction into running process`);
      return 'injected';
    }

    // Process is not running or turn is active — kill and recreate state.
    // The next handleChat() will start a fresh process with the correct --permission-mode.
    const wasTurnActive = existing.turnActive;
    const lastSession = existing.claudeSessionId || existing.lastClaudeSessionId;
    const workDir = existing.workDir;

    cleanupConversation(convId);

    // Notify UI if we interrupted an active turn
    if (wasTurnActive) {
      sendFn({ type: 'execution_cancelled', conversationId: convId });
    }

    const newState: ConversationState = {
      child: null,
      inputStream: null,
      abortController: null,
      claudeSessionId: null,
      workDir,
      turnActive: false,
      turnResultReceived: false,
      conversationId: convId,
      lastClaudeSessionId: lastSession || null,
      isCompacting: false,
      createdAt: Date.now(),
      planMode: enteringPlan,
      brainMode: false,
    };
    conversations.set(convId, newState);
    return 'immediate';
  } else {
    // No existing conversation yet (e.g. user toggled plan mode before first message).
    // Create a placeholder so handleChat()/startQuery() picks up the plan mode.
    const placeholder: ConversationState = {
      child: null,
      inputStream: null,
      abortController: null,
      claudeSessionId: null,
      workDir: '',  // will be overridden by handleChat's workDir param
      turnActive: false,
      turnResultReceived: false,
      conversationId: convId,
      lastClaudeSessionId: claudeSessionId || null,
      isCompacting: false,
      createdAt: Date.now(),
      planMode: enteringPlan,
      brainMode: false,
    };
    conversations.set(convId, placeholder);
    return 'immediate';
  }
}

function processFilesForClaude(files: ChatFile[], workDir: string, prompt: string): unknown[] {
  const attachDir = join(CONFIG_DIR, 'tmp-attachments');
  if (!existsSync(attachDir)) {
    mkdirSync(attachDir, { recursive: true });
  }

  const content: unknown[] = [];
  const nonImagePaths: string[] = [];

  for (const file of files) {
    const timestamp = Date.now();
    const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_');
    const diskName = `${timestamp}-${safeName}`;
    const diskPath = join(attachDir, diskName);

    // Write file to disk
    writeFileSync(diskPath, Buffer.from(file.data, 'base64'));
    console.log(`[Claude] Saved attachment: ${diskPath}`);

    if (file.mimeType.startsWith('image/')) {
      // Images: send as inline base64 content blocks
      content.push({
        type: 'image',
        source: {
          type: 'base64',
          media_type: file.mimeType,
          data: file.data,
        },
      });
    } else {
      // Non-images: reference by file path
      nonImagePaths.push(diskPath);
    }
  }

  // Build text block with prompt + file references
  let textContent = prompt;
  if (nonImagePaths.length > 0) {
    textContent += '\n\nAttached files:\n' + nonImagePaths.map(p => `- ${p}`).join('\n');
  }
  content.push({ type: 'text', text: textContent });

  return content;
}

function startQuery(conversationId: string, workDir: string, resumeSessionId?: string, brainMode?: boolean): void {
  // Tear down previous process for THIS conversation only (not others)
  const existing = conversations.get(conversationId);
  console.log(`[Claude:${conversationId.slice(0, 8)}] startQuery: existing=${!!existing}, existing.planMode=${existing?.planMode}`);
  if (existing) {
    abort(conversationId);
  }
  console.log(`[Claude:${conversationId.slice(0, 8)}] startQuery after abort: existing.planMode=${existing?.planMode}`);

  // Evict oldest idle conversation if at capacity (quota-aware)
  const convType = isLoopConversation(conversationId) ? 'loop' : 'chat';
  const maxForType = convType === 'loop' ? MAX_LOOP_CONVERSATIONS : MAX_CHAT_CONVERSATIONS;
  if (getConversationCount(convType) >= maxForType) {
    evictOldestIdle(conversationId, convType);
  }

  const inputStream = new Stream<ClaudeMessage>();
  const abortController = new AbortController();

  const state: ConversationState = {
    child: null,
    inputStream,
    abortController,
    claudeSessionId: resumeSessionId || null,
    workDir,
    turnActive: false,
    turnResultReceived: false,
    conversationId,
    lastClaudeSessionId: existing?.lastClaudeSessionId || null,
    isCompacting: false,
    createdAt: Date.now(),
    planMode: existing?.planMode || false,
    brainMode: brainMode || existing?.brainMode || false,
  };

  conversations.set(conversationId, state);

  // Build args
  // In normal mode: bypassPermissions auto-approves all regular tool calls.
  // In plan mode: use native 'plan' permission mode — Claude's system prompt
  // knows it's in plan mode and self-enforces read-only behavior.
  // --permission-prompt-tool stdio tells Claude CLI to send control_request
  // via stdout for interactive tools (like AskUserQuestion) instead of
  // auto-denying them.
  const permissionMode = state.planMode ? 'plan' : 'bypassPermissions';
  const args = [
    '--output-format', 'stream-json',
    '--input-format', 'stream-json',
    '--verbose',
    '--permission-mode', permissionMode,
    '--permission-prompt-tool', 'stdio',
  ];

  console.log(`[Claude:${conversationId.slice(0, 8)}] planMode=${state.planMode}, permissionMode=${permissionMode}`);

  if (resumeSessionId) {
    args.push('--resume', resumeSessionId);
    console.log(`[Claude:${conversationId.slice(0, 8)}] Resuming session: ${resumeSessionId}`);
  }

  const { command, prefixArgs, spawnOpts } = state.brainMode
    ? { command: 'brain', prefixArgs: [] as string[], spawnOpts: { shell: true } }
    : resolveClaudeCommand();
  const env = getCleanEnv();

  console.log(`[Claude:${conversationId.slice(0, 8)}] Spawning: ${command} ${[...prefixArgs, ...args].join(' ')}`);
  console.log(`[Claude:${conversationId.slice(0, 8)}] cwd: ${workDir}`);

  const child = spawn(command, [...prefixArgs, ...args], {
    cwd: workDir,
    stdio: ['pipe', 'pipe', 'pipe'],
    signal: abortController.signal,
    env,
    ...spawnOpts,
    windowsHide: true, // must come after spread to prevent override
  });

  state.child = child;

  // Pipe user messages → stdin
  streamToStdin(inputStream, child.stdin, abortController.signal);

  // Capture stderr for debugging (use object so processOutput sees updates)
  const stderr = { buf: '' };
  child.stderr.on('data', (data: Buffer) => {
    const text = data.toString();
    stderr.buf += text;
    if (process.env.DEBUG) console.error('[Claude stderr]', text);
  });

  // Process stdout (JSON lines)
  processOutput(child, state, stderr);

  // Handle process exit
  child.on('close', (code) => {
    if (code !== 0 && code !== null && !abortController.signal.aborted) {
      const msg = stderr.buf
        ? `Claude process exited with code ${code}: ${stderr.buf.trim()}`
        : `Claude process exited with code ${code}`;
      console.error(`[Claude:${conversationId.slice(0, 8)}] ${msg}`);
    }
  });

  child.on('error', (err) => {
    if (!abortController.signal.aborted) {
      console.error(`[Claude:${conversationId.slice(0, 8)}] Process error: ${err.message}`);
    }
  });
}

/**
 * Evict the oldest idle conversation of the given type to make room for a new one.
 * Only evicts conversations that are NOT actively processing (turnActive === false).
 * If all same-type conversations are active, evicts the oldest one regardless.
 */
function evictOldestIdle(excludeId: string, convType: 'chat' | 'loop'): void {
  let oldest: { id: string; createdAt: number } | null = null;
  let oldestIdle: { id: string; createdAt: number } | null = null;
  const maxForType = convType === 'loop' ? MAX_LOOP_CONVERSATIONS : MAX_CHAT_CONVERSATIONS;

  for (const [id, conv] of conversations) {
    if (id === excludeId) continue;
    // Only consider same-type conversations
    const sameType = convType === 'loop' ? isLoopConversation(id) : !isLoopConversation(id);
    if (!sameType) continue;

    if (!oldest || conv.createdAt < oldest.createdAt) {
      oldest = { id, createdAt: conv.createdAt };
    }
    if (!conv.turnActive && (!oldestIdle || conv.createdAt < oldestIdle.createdAt)) {
      oldestIdle = { id, createdAt: conv.createdAt };
    }
  }

  const target = oldestIdle || oldest;
  if (target) {
    console.log(`[Claude] Evicting ${convType} conversation ${target.id.slice(0, 8)} (capacity: ${getConversationCount(convType)}/${maxForType})`);
    abort(target.id);
  }
}

// ── Message processing helpers moved to claude-message-helpers.ts ────────

async function processOutput(
  child: ChildProcess,
  state: ConversationState,
  stderr: { buf: string },
): Promise<void> {
  const rl = createInterface({ input: child.stdout! });
  const messageStream = new Stream<ClaudeMessage>();

  // Reader: parse JSON lines from stdout → messageStream
  (async () => {
    try {
      for await (const line of rl) {
        if (!line.trim()) continue;
        try {
          const msg: ClaudeMessage = JSON.parse(line);

          // Notify output observers before any processing.
          // If any observer returns true, suppress this message from normal handling.
          let suppressed = false;
          for (const observer of outputObservers) {
            if (observer(state.conversationId, msg)) {
              suppressed = true;
            }
          }
          if (suppressed) {
            continue;
          }

          // Capture session ID from system init
          if (msg.type === 'system' && msg.session_id) {
            state.claudeSessionId = msg.session_id as string;
            state.lastClaudeSessionId = state.claudeSessionId;
            console.log(`[Claude:${state.conversationId.slice(0, 8)}] Session ID: ${state.claudeSessionId}`);
            // Notify web client so sidebar can refresh session list
            sendWithConvId({ type: 'session_started', claudeSessionId: state.claudeSessionId });
            // Persist brain mode metadata to disk
            if (state.brainMode) {
              saveSessionMetadata(state.claudeSessionId, { brainMode: true });
            }
          }

          // Handle control_request (tool permission checks)
          if (msg.type === 'control_request') {
            handleControlRequest(msg as unknown as ControlRequest, child, state.conversationId);
            continue;
          }

          // Handle control_cancel_request (abort pending questions)
          if (msg.type === 'control_cancel_request') {
            const reqId = (msg as unknown as { request_id: string }).request_id;
            if (pendingControlRequests.has(reqId)) {
              console.log(`[Claude:${state.conversationId.slice(0, 8)}] Control request cancelled: ${reqId}`);
              pendingControlRequests.delete(reqId);
            }
            continue;
          }

          // Ignore control_response (responses to our own requests, if any)
          if (msg.type === 'control_response') {
            continue;
          }

          messageStream.enqueue(msg);
        } catch {
          // Non-JSON line, ignore
        }
      }
    } catch (err) {
      messageStream.error(err);
    } finally {
      messageStream.done();
      rl.close();
    }
  })();

  // Helper: send message with conversationId
  function sendWithConvId(msg: Record<string, unknown>): void {
    sendFn({ ...msg, conversationId: state.conversationId });
  }

  // Consumer: iterate messages and forward to web client
  let resultHandled = false;
  // Track accumulated text for streaming delta computation
  let lastSentText = '';
  // Suppress output for turns triggered by task-notification (background task events)
  let silentTurn = false;

  try {
    for await (const msg of messageStream) {
      // If the conversation was cancelled/removed, stop processing stale output
      if (conversations.get(state.conversationId) !== state) {
        break;
      }

      // ── result → turn complete ──
      if (msg.type === 'result') {
        if (state.turnResultReceived) {
          // Suppress duplicate result (SDK can emit more than one)
          continue;
        }
        state.turnResultReceived = true;
        resultHandled = true;
        lastSentText = '';

        if (silentTurn) {
          // Silent turn (task-notification) — clean up without notifying UI
          silentTurn = false;
          state.turnActive = false;
          console.log(`[Claude:${state.conversationId.slice(0, 8)}] Silent turn completed — no output forwarded to UI`);
          continue;
        }

        handleResultMessage(msg, state, sendWithConvId);
        continue;
      }

      // ── assistant message → extract delta and forward incrementally ──
      if (msg.type === 'assistant' && msg.message) {
        if (silentTurn) continue;

        lastSentText = handleAssistantMessage(msg, lastSentText, sendWithConvId);

        // Detect EnterPlanMode/ExitPlanMode tool calls — Claude is toggling
        // plan mode natively. Sync state and notify the web UI.
        const msgContent = (msg.message as { content?: Array<Record<string, unknown>> }).content;
        if (Array.isArray(msgContent)) {
          const hasExitPlan = msgContent.some(
            (b) => b.type === 'tool_use' && b.name === 'ExitPlanMode'
          );
          const hasEnterPlan = msgContent.some(
            (b) => b.type === 'tool_use' && b.name === 'EnterPlanMode'
          );
          if (hasExitPlan && state.planMode) {
            console.log(`[Claude:${state.conversationId.slice(0, 8)}] ExitPlanMode detected — switching to normal mode`);
            state.planMode = false;
            sendWithConvId({ type: 'plan_mode_changed', enabled: false });
          } else if (hasEnterPlan && !state.planMode) {
            console.log(`[Claude:${state.conversationId.slice(0, 8)}] EnterPlanMode detected — switching to plan mode`);
            state.planMode = true;
            sendWithConvId({ type: 'plan_mode_changed', enabled: true });
          }
        }

        continue;
      }

      // ── user (tool_result) → forward, reset text tracker ──
      if (msg.type === 'user') {
        lastSentText = '';
        if (isTaskNotification(msg)) {
          silentTurn = true;
          console.log(`[Claude:${state.conversationId.slice(0, 8)}] task-notification detected — entering silent turn`);
          continue;
        }
        if (silentTurn) continue;
        if (handleUserMessage(msg, sendWithConvId)) continue;
        continue;
      }

      // ── system messages (init, compact, etc.) ──
      if (msg.type === 'system') {
        const sub = (msg.subtype || '') as string;
        console.log(`[Claude:${state.conversationId.slice(0, 8)}] system/${sub}`);

        if (silentTurn) {
          // During silent turns, update internal state but don't notify UI
          if (sub === 'status' && msg.status === 'compacting') state.isCompacting = true;
          else if (sub === 'compact_boundary' || sub === 'compact_complete' || sub === 'compact_end') state.isCompacting = false;
          else if (sub === 'compact_start') state.isCompacting = true;
          continue;
        }

        // Forward context compaction events to web client
        // New format: subtype='status', status='compacting'
        if (sub === 'status' && msg.status === 'compacting') {
          state.isCompacting = true;
          sendWithConvId({ type: 'context_compaction', status: 'started' });
        }
        // Compact boundary = compaction completed
        else if (sub === 'compact_boundary') {
          state.isCompacting = false;
          sendWithConvId({ type: 'context_compaction', status: 'completed' });
        }
        // Legacy subtypes
        else if (sub === 'compact_start') {
          state.isCompacting = true;
          sendWithConvId({ type: 'context_compaction', status: 'started' });
        } else if (sub === 'compact_complete' || sub === 'compact_end') {
          state.isCompacting = false;
          sendWithConvId({ type: 'context_compaction', status: 'completed' });
        }
        continue;
      }
    }
  } catch (err) {
    const error = err as Error;
    if (error.name === 'AbortError') {
      console.log(`[Claude:${state.conversationId.slice(0, 8)}] Query aborted`);
    } else if (resultHandled) {
      // Ignore post-turn errors
      console.warn(`[Claude:${state.conversationId.slice(0, 8)}] Ignoring post-result error: ${error.message}`);
    } else {
      console.error(`[Claude:${state.conversationId.slice(0, 8)}] Error: ${error.message}`);
      sendWithConvId({
        type: 'error',
        message: `Claude error: ${error.message}`,
      });
    }
  } finally {
    // If the process exited mid-turn without a result, notify web client with error
    if (!resultHandled && state.turnActive && !silentTurn) {
      if (stderr.buf.trim()) {
        sendWithConvId({ type: 'error', message: stderr.buf.trim() });
      }
      sendWithConvId({ type: 'turn_completed' });
    }
    state.turnActive = false;

    // Notify close observers (used by team + scheduler modules)
    for (const observer of closeObservers) {
      observer(state.conversationId, child.exitCode, resultHandled);
    }

    // Only clean up if this conversation is still in the map with the same state
    if (conversations.get(state.conversationId) === state) {
      state.child = null;
      state.inputStream = null;
    }
  }
}

/**
 * Handle an incoming control_request from Claude's stdout.
 * For AskUserQuestion: forward to web UI and wait for user answer.
 * For other tools: auto-approve immediately.
 * Note: plan mode tool restrictions are handled natively by Claude's
 * --permission-mode plan flag — no custom deny logic needed here.
 */
function handleControlRequest(
  request: ControlRequest,
  child: ChildProcess,
  conversationId: string,
): void {
  const requestId = request.request_id;
  const subtype = request.request?.subtype;
  const toolName = request.request.tool_name;

  if (subtype === 'can_use_tool' && toolName === 'AskUserQuestion') {
    console.log(`[Claude:${conversationId.slice(0, 8)}] AskUserQuestion control_request: ${requestId}`);
    pendingControlRequests.set(requestId, { request, child, conversationId });

    // Forward to web UI
    sendFn({
      type: 'ask_user_question',
      conversationId,
      requestId,
      questions: (request.request.input as Record<string, unknown>)?.questions || [],
    });
    return;
  }

  // Auto-approve all other tool calls
  const response = buildControlResponse(requestId, request.request.input || {});

  if (child.stdin && !child.stdin.destroyed) {
    child.stdin.write(JSON.stringify(response) + '\n');
  }
}

/**
 * Clean up a specific conversation: kill process, clear pending requests, remove from map.
 */
function cleanupConversation(conversationId: string): void {
  const conv = conversations.get(conversationId);
  if (!conv) return;

  // Clear pending control requests belonging to this conversation
  for (const [reqId, pending] of pendingControlRequests) {
    if (pending.conversationId === conversationId) {
      pendingControlRequests.delete(reqId);
    }
  }

  conv.isCompacting = false;

  // Preserve session ID so the next message can resume
  if (conv.claudeSessionId) {
    conv.lastClaudeSessionId = conv.claudeSessionId;
  }

  if (conv.child && !conv.child.killed) {
    const pid = conv.child.pid;
    // On Windows, kill the entire process tree (child.kill() won't kill grandchildren)
    if (pid && process.platform === 'win32') {
      try {
        execSync(`taskkill /pid ${pid} /t /f`, { stdio: 'ignore', windowsHide: true });
      } catch { /* process may have already exited */ }
    } else {
      conv.child.kill();
    }
  }
  if (conv.inputStream) {
    conv.inputStream.done();
  }

  conversations.delete(conversationId);
}
