/**
 * Claude Code SDK integration.
 *
 * Spawns `claude` as a child process with --output-format stream-json
 * and --input-format stream-json for persistent bidirectional communication.
 *
 * Supports multiple concurrent conversations, each with its own Claude process.
 * Conversations are keyed by conversationId (a UUID generated by the web client).
 * When no conversationId is provided (backward compat), uses 'default' as the key.
 *
 * Lifecycle:
 *   1.  Web user sends first message → startQuery() spawns Claude process
 *   2.  Each user message is enqueued into the inputStream
 *   3.  processOutput() iterates Claude stdout, forwarding messages via sendFn
 *   4.  On 'result' message → turn is complete, process stays alive for next turn
 *   5.  On abort / process exit → cleanup
 */

import { spawn, execSync, type ChildProcess } from 'child_process';
import { createInterface } from 'readline';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { Stream } from './stream.js';
import {
  resolveClaudeCommand,
  getCleanEnv,
  streamToStdin,
} from './sdk.js';
import { CONFIG_DIR } from './config.js';

// ── Types ──────────────────────────────────────────────────────────────────

export interface ClaudeMessage {
  type: string;
  subtype?: string;
  [key: string]: unknown;
}

export interface ChatFile {
  name: string;
  mimeType: string;
  data: string; // base64
}

export interface ConversationState {
  child: ChildProcess | null;
  inputStream: Stream<ClaudeMessage> | null;
  abortController: AbortController | null;
  claudeSessionId: string | null;
  workDir: string;
  turnActive: boolean;
  turnResultReceived: boolean;
  // Multi-session fields
  conversationId: string;
  lastClaudeSessionId: string | null;
  isCompacting: boolean;
  createdAt: number;
}

type SendFn = (msg: Record<string, unknown>) => void;

// ── Control request types ──────────────────────────────────────────────────

interface ControlRequest {
  type: 'control_request';
  request_id: string;
  request: {
    subtype: string;
    tool_name?: string;
    input?: Record<string, unknown>;
  };
}

interface PendingControlRequest {
  request: ControlRequest;
  child: ChildProcess;
  conversationId: string;
}

// ── Constants ─────────────────────────────────────────────────────────────

const DEFAULT_CONVERSATION_ID = 'default';
export const MAX_CHAT_CONVERSATIONS = 15;
export const MAX_LOOP_CONVERSATIONS = 3;

/** @deprecated Use MAX_CHAT_CONVERSATIONS instead. Kept for backward compat. */
export const MAX_CONVERSATIONS = MAX_CHAT_CONVERSATIONS;

function isLoopConversation(conversationId: string): boolean {
  return conversationId.startsWith('loop-');
}

function getConversationCount(type: 'chat' | 'loop'): number {
  let count = 0;
  for (const [id] of conversations) {
    if (type === 'loop' && isLoopConversation(id)) count++;
    if (type === 'chat' && !isLoopConversation(id)) count++;
  }
  return count;
}

// ── Helpers ──────────────────────────────────────────────────────────────

/** Build a control_response JSON payload for writing to Claude's stdin. */
export function buildControlResponse(
  requestId: string,
  updatedInput: Record<string, unknown>,
): Record<string, unknown> {
  return {
    type: 'control_response',
    response: {
      subtype: 'success',
      request_id: requestId,
      response: {
        behavior: 'allow',
        updatedInput,
      },
    },
  };
}

// ── Module state ───────────────────────────────────────────────────────────

const conversations = new Map<string, ConversationState>();
let sendFn: SendFn = () => {};
const pendingControlRequests = new Map<string, PendingControlRequest>();

// ── Output observer chain ──────────────────────────────────────────────────
// Callbacks invoked for every parsed JSON line from Claude stdout.
// Receives (conversationId, rawMessage). If any observer returns true, the
// message is suppressed from normal forwarding to the web client.
// Multiple observers can be registered (e.g., team + loop).

type OutputObserverFn = (conversationId: string, msg: ClaudeMessage) => boolean | void;
const outputObservers: OutputObserverFn[] = [];

export function addOutputObserver(fn: OutputObserverFn): void {
  outputObservers.push(fn);
}

export function removeOutputObserver(fn: OutputObserverFn): void {
  const idx = outputObservers.indexOf(fn);
  if (idx >= 0) outputObservers.splice(idx, 1);
}

/** @deprecated Use addOutputObserver() instead. Kept for backward compat (team.ts). */
export function setOutputObserver(fn: OutputObserverFn): void {
  addOutputObserver(fn);
}

/** @deprecated Use removeOutputObserver() instead. Clears ALL observers. */
export function clearOutputObserver(): void {
  outputObservers.length = 0;
}

// ── Close observer chain ──────────────────────────────────────────────────
// Callbacks invoked when a Claude process exits. Receives
// (conversationId, exitCode, resultReceived). Allows the team module to
// detect Lead crashes and the scheduler to detect Loop process exits.

type CloseObserverFn = (conversationId: string, exitCode: number | null, resultReceived: boolean) => void;
const closeObservers: CloseObserverFn[] = [];

export function addCloseObserver(fn: CloseObserverFn): void {
  closeObservers.push(fn);
}

export function removeCloseObserver(fn: CloseObserverFn): void {
  const idx = closeObservers.indexOf(fn);
  if (idx >= 0) closeObservers.splice(idx, 1);
}

/** @deprecated Use addCloseObserver() instead. Kept for backward compat (team.ts). */
export function setCloseObserver(fn: CloseObserverFn): void {
  addCloseObserver(fn);
}

/** @deprecated Use removeCloseObserver() instead. Clears ALL close observers. */
export function clearCloseObserver(): void {
  closeObservers.length = 0;
}

export function setSendFn(fn: SendFn): void {
  sendFn = fn;
}

/**
 * Get a conversation by its conversationId.
 * If no conversationId is provided, returns the 'default' conversation (backward compat).
 */
export function getConversation(conversationId?: string): ConversationState | null {
  return conversations.get(conversationId || DEFAULT_CONVERSATION_ID) || null;
}

/** Get all active conversations. */
export function getConversations(): Map<string, ConversationState> {
  return conversations;
}

/**
 * Evict any idle conversation that holds the given claudeSessionId.
 * Returns true if a busy (turnActive) conversation blocked the eviction.
 */
export function evictByClaudeSessionId(claudeSessionId: string): boolean {
  for (const [convId, conv] of conversations) {
    if (conv.claudeSessionId === claudeSessionId || conv.lastClaudeSessionId === claudeSessionId) {
      if (conv.turnActive) return true; // busy — caller should block
      cleanupConversation(convId);
    }
  }
  return false;
}

/**
 * Rebind a running conversation to a new conversationId.
 * Finds the conversation by claudeSessionId and remaps its key in the Map.
 * Used when the web client reconnects (page refresh) with a new conversationId.
 */
export function rebindConversation(claudeSessionId: string, newConvId: string): boolean {
  if (conversations.has(newConvId)) {
    return false;
  }
  for (const [oldConvId, conv] of conversations) {
    if ((conv.claudeSessionId === claudeSessionId || conv.lastClaudeSessionId === claudeSessionId)
        && oldConvId !== newConvId) {
      conversations.delete(oldConvId);
      conv.conversationId = newConvId;
      conversations.set(newConvId, conv);
      // Update pending control requests that reference the old conversationId
      for (const pending of pendingControlRequests.values()) {
        if (pending.conversationId === oldConvId) {
          pending.conversationId = newConvId;
        }
      }
      console.log(`[Claude] Rebound conversation ${oldConvId.slice(0, 8)} → ${newConvId.slice(0, 8)} (session ${claudeSessionId.slice(0, 8)})`);
      return true;
    }
  }
  return false;
}

/** Whether context compaction is currently in progress for a conversation. */
export function getIsCompacting(conversationId?: string): boolean {
  const conv = conversations.get(conversationId || DEFAULT_CONVERSATION_ID);
  return conv?.isCompacting ?? false;
}

/**
 * Clear the saved session ID for a conversation.
 * If no conversationId is provided, clears all (backward compat).
 */
export function clearSessionId(conversationId?: string): void {
  if (conversationId) {
    const conv = conversations.get(conversationId);
    if (conv) {
      conv.lastClaudeSessionId = null;
    }
  } else {
    for (const conv of conversations.values()) {
      conv.lastClaudeSessionId = null;
    }
  }
}

// ── Public API ─────────────────────────────────────────────────────────────

/** Options for handleChat() */
export interface HandleChatOptions {
  resumeSessionId?: string;
  extraArgs?: string[];
}

/**
 * Handle a chat message from the web client.
 * Lazily starts the Claude process on the first message.
 * If resumeSessionId is provided, resumes that Claude session.
 * If extraArgs is provided, they are appended to the Claude CLI args on spawn.
 */
export function handleChat(
  conversationId: string | undefined,
  prompt: string,
  workDir: string,
  options?: HandleChatOptions,
  files?: ChatFile[],
): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const existing = conversations.get(convId);

  if (!existing || !existing.inputStream) {
    // If the process exited but we still know the session ID, resume it
    const sessionToResume = options?.resumeSessionId || existing?.claudeSessionId || existing?.lastClaudeSessionId || undefined;
    startQuery(convId, workDir, sessionToResume, options?.extraArgs);
  }

  const state = conversations.get(convId)!;
  state.turnActive = true;
  state.turnResultReceived = false;

  console.log(`[Claude:${convId.slice(0, 8)}] Sending: ${prompt.substring(0, 100)}${prompt.length > 100 ? '...' : ''}`);

  if (files && files.length > 0) {
    const content = processFilesForClaude(files, workDir, prompt);
    state.inputStream!.enqueue({
      type: 'user',
      message: { role: 'user', content },
    });
  } else {
    state.inputStream!.enqueue({
      type: 'user',
      message: { role: 'user', content: prompt },
    });
  }
}

/**
 * Abort a specific conversation's Claude process.
 * If no conversationId, aborts the 'default' conversation (backward compat).
 */
export function abort(conversationId?: string): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  if (!conv) return;

  if (conv.abortController) {
    conv.abortController.abort();
  }
  cleanupConversation(convId);
}

/**
 * Abort all conversations (used on agent shutdown).
 */
export function abortAll(): void {
  for (const convId of [...conversations.keys()]) {
    abort(convId);
  }
}

/**
 * Cancel the current execution for a conversation (user pressed stop button).
 * Kills the process and notifies the web client.
 */
export function cancelExecution(conversationId?: string): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  if (!conv) return;

  console.log(`[Claude:${convId.slice(0, 8)}] Cancelling execution`);
  conv.turnActive = false;

  if (conv.abortController) {
    conv.abortController.abort();
  }
  cleanupConversation(convId);

  sendFn({ type: 'execution_cancelled', conversationId: convId });
}

/**
 * Handle the user's answer to an AskUserQuestion control request.
 * Writes a control_response back to Claude's stdin.
 */
export function handleUserAnswer(requestId: string, answers: Record<string, unknown>): void {
  const pending = pendingControlRequests.get(requestId);
  if (!pending) {
    console.warn(`[Claude] No pending control request for requestId: ${requestId}`);
    return;
  }

  pendingControlRequests.delete(requestId);
  console.log(`[Claude] Answering AskUserQuestion ${requestId}`);

  const response = buildControlResponse(pending.request.request_id, {
    questions: pending.request.request.input?.questions || [],
    answers,
  });

  if (pending.child.stdin && !pending.child.stdin.destroyed) {
    pending.child.stdin.write(JSON.stringify(response) + '\n');
  }
}

/**
 * Handle a /btw side question. Spawns a lightweight, ephemeral Claude query
 * that resumes the current conversation's session for context but does not
 * persist any changes. Streams btw_answer deltas back to the web client.
 */
export async function handleBtwQuestion(
  question: string,
  conversationId: string | undefined,
  workDir: string,
  send: (msg: Record<string, unknown>) => void,
): Promise<void> {
  // 1. Find the session ID for context from the conversations map
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  const sessionId = conv?.claudeSessionId || conv?.lastClaudeSessionId || null;

  if (!sessionId) {
    send({ type: 'btw_answer', delta: 'No active conversation context available.', done: true });
    return;
  }

  const effectiveWorkDir = conv?.workDir || workDir;

  // 2. Build args for a lightweight one-shot query
  const args = [
    '-p', question,
    '--resume', sessionId,
    '--no-session-persistence',
    '--output-format', 'stream-json',
  ];

  const { command, prefixArgs, spawnOpts } = resolveClaudeCommand();
  const env = getCleanEnv();

  console.log(`[Claude:btw] Spawning side question (session ${sessionId.slice(0, 8)}): ${question.substring(0, 80)}`);

  let child: ChildProcess;
  try {
    child = spawn(command, [...prefixArgs, ...args], {
      cwd: effectiveWorkDir,
      stdio: ['pipe', 'pipe', 'pipe'],
      env,
      ...spawnOpts,
      windowsHide: true,
    });
  } catch (err) {
    send({ type: 'btw_answer', delta: `Failed to spawn Claude: ${(err as Error).message}`, done: true });
    return;
  }

  // Close stdin immediately — this is a one-shot -p query, no interactive input needed
  if (child.stdin) {
    child.stdin.end();
  }

  // 3. Parse streaming JSON output and forward text deltas
  const rl = createInterface({ input: child.stdout! });
  let lastSentText = '';
  let sentAnyDelta = false;

  const stderrBuf: string[] = [];
  child.stderr?.on('data', (data: Buffer) => {
    stderrBuf.push(data.toString());
  });

  try {
    for await (const line of rl) {
      if (!line.trim()) continue;
      let msg: ClaudeMessage;
      try {
        msg = JSON.parse(line);
      } catch {
        continue;
      }

      // Extract text deltas from assistant messages
      if (msg.type === 'assistant' && msg.message) {
        const message = msg.message as { content?: Array<Record<string, unknown>> };
        const content = message.content;
        if (!Array.isArray(content)) continue;

        const fullText = content
          .filter((b) => b.type === 'text')
          .map((b) => (b.text as string) || '')
          .join('');

        if (fullText.length > lastSentText.length) {
          const delta = fullText.slice(lastSentText.length);
          lastSentText = fullText;
          sentAnyDelta = true;
          send({ type: 'btw_answer', delta, done: false });
        }
      }

      // On result, mark done
      if (msg.type === 'result') {
        // If result contains text we haven't sent yet
        if (typeof msg.result === 'string' && msg.result.length > lastSentText.length) {
          const delta = msg.result.slice(lastSentText.length);
          send({ type: 'btw_answer', delta, done: true });
        } else {
          send({ type: 'btw_answer', delta: '', done: true });
        }
        rl.close();
        return;
      }
    }
  } catch (err) {
    const error = err as Error;
    if (error.name !== 'AbortError') {
      console.error(`[Claude:btw] Stream error: ${error.message}`);
    }
  } finally {
    rl.close();
  }

  // If we reach here without sending done (process exited without result message)
  if (!sentAnyDelta) {
    const stderrText = stderrBuf.join('').trim();
    const errorMsg = stderrText || 'Side question failed — no response received.';
    send({ type: 'btw_answer', delta: errorMsg, done: true });
  } else {
    send({ type: 'btw_answer', delta: '', done: true });
  }
}

// ── Internal ───────────────────────────────────────────────────────────────

function processFilesForClaude(files: ChatFile[], workDir: string, prompt: string): unknown[] {
  const attachDir = join(CONFIG_DIR, 'tmp-attachments');
  if (!existsSync(attachDir)) {
    mkdirSync(attachDir, { recursive: true });
  }

  const content: unknown[] = [];
  const nonImagePaths: string[] = [];

  for (const file of files) {
    const timestamp = Date.now();
    const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_');
    const diskName = `${timestamp}-${safeName}`;
    const diskPath = join(attachDir, diskName);

    // Write file to disk
    writeFileSync(diskPath, Buffer.from(file.data, 'base64'));
    console.log(`[Claude] Saved attachment: ${diskPath}`);

    if (file.mimeType.startsWith('image/')) {
      // Images: send as inline base64 content blocks
      content.push({
        type: 'image',
        source: {
          type: 'base64',
          media_type: file.mimeType,
          data: file.data,
        },
      });
    } else {
      // Non-images: reference by file path
      nonImagePaths.push(diskPath);
    }
  }

  // Build text block with prompt + file references
  let textContent = prompt;
  if (nonImagePaths.length > 0) {
    textContent += '\n\nAttached files:\n' + nonImagePaths.map(p => `- ${p}`).join('\n');
  }
  content.push({ type: 'text', text: textContent });

  return content;
}

function startQuery(conversationId: string, workDir: string, resumeSessionId?: string, extraArgs?: string[]): void {
  // Tear down previous process for THIS conversation only (not others)
  const existing = conversations.get(conversationId);
  if (existing) {
    abort(conversationId);
  }

  // Evict oldest idle conversation if at capacity (quota-aware)
  const convType = isLoopConversation(conversationId) ? 'loop' : 'chat';
  const maxForType = convType === 'loop' ? MAX_LOOP_CONVERSATIONS : MAX_CHAT_CONVERSATIONS;
  if (getConversationCount(convType) >= maxForType) {
    evictOldestIdle(conversationId, convType);
  }

  const inputStream = new Stream<ClaudeMessage>();
  const abortController = new AbortController();

  const state: ConversationState = {
    child: null,
    inputStream,
    abortController,
    claudeSessionId: resumeSessionId || null,
    workDir,
    turnActive: false,
    turnResultReceived: false,
    conversationId,
    lastClaudeSessionId: existing?.lastClaudeSessionId || null,
    isCompacting: false,
    createdAt: Date.now(),
  };

  conversations.set(conversationId, state);

  // Build args
  // bypassPermissions auto-approves all regular tool calls.
  // --permission-prompt-tool stdio tells Claude CLI to send control_request
  // via stdout for interactive tools (like AskUserQuestion) instead of
  // auto-denying them. Our handleControlRequest() intercepts these and
  // either auto-approves or forwards to the web UI.
  const args = [
    '--output-format', 'stream-json',
    '--input-format', 'stream-json',
    '--verbose',
    '--permission-mode', 'bypassPermissions',
    '--permission-prompt-tool', 'stdio',
  ];

  if (resumeSessionId) {
    args.push('--resume', resumeSessionId);
    console.log(`[Claude:${conversationId.slice(0, 8)}] Resuming session: ${resumeSessionId}`);
  }

  if (extraArgs && extraArgs.length > 0) {
    args.push(...extraArgs);
    console.log(`[Claude:${conversationId.slice(0, 8)}] Extra args: ${extraArgs.join(' ')}`);
  }

  const { command, prefixArgs, spawnOpts } = resolveClaudeCommand();
  const env = getCleanEnv();

  console.log(`[Claude:${conversationId.slice(0, 8)}] Spawning: ${command} ${[...prefixArgs, ...args].join(' ')}`);
  console.log(`[Claude:${conversationId.slice(0, 8)}] cwd: ${workDir}`);

  const child = spawn(command, [...prefixArgs, ...args], {
    cwd: workDir,
    stdio: ['pipe', 'pipe', 'pipe'],
    signal: abortController.signal,
    env,
    ...spawnOpts,
    windowsHide: true, // must come after spread to prevent override
  });

  state.child = child;

  // Pipe user messages → stdin
  streamToStdin(inputStream, child.stdin, abortController.signal);

  // Capture stderr for debugging (use object so processOutput sees updates)
  const stderr = { buf: '' };
  child.stderr.on('data', (data: Buffer) => {
    const text = data.toString();
    stderr.buf += text;
    if (process.env.DEBUG) console.error('[Claude stderr]', text);
  });

  // Process stdout (JSON lines)
  processOutput(child, state, stderr);

  // Handle process exit
  child.on('close', (code) => {
    if (code !== 0 && code !== null && !abortController.signal.aborted) {
      const msg = stderr.buf
        ? `Claude process exited with code ${code}: ${stderr.buf.trim()}`
        : `Claude process exited with code ${code}`;
      console.error(`[Claude:${conversationId.slice(0, 8)}] ${msg}`);
    }
  });

  child.on('error', (err) => {
    if (!abortController.signal.aborted) {
      console.error(`[Claude:${conversationId.slice(0, 8)}] Process error: ${err.message}`);
    }
  });
}

/**
 * Evict the oldest idle conversation of the given type to make room for a new one.
 * Only evicts conversations that are NOT actively processing (turnActive === false).
 * If all same-type conversations are active, evicts the oldest one regardless.
 */
function evictOldestIdle(excludeId: string, convType: 'chat' | 'loop'): void {
  let oldest: { id: string; createdAt: number } | null = null;
  let oldestIdle: { id: string; createdAt: number } | null = null;
  const maxForType = convType === 'loop' ? MAX_LOOP_CONVERSATIONS : MAX_CHAT_CONVERSATIONS;

  for (const [id, conv] of conversations) {
    if (id === excludeId) continue;
    // Only consider same-type conversations
    const sameType = convType === 'loop' ? isLoopConversation(id) : !isLoopConversation(id);
    if (!sameType) continue;

    if (!oldest || conv.createdAt < oldest.createdAt) {
      oldest = { id, createdAt: conv.createdAt };
    }
    if (!conv.turnActive && (!oldestIdle || conv.createdAt < oldestIdle.createdAt)) {
      oldestIdle = { id, createdAt: conv.createdAt };
    }
  }

  const target = oldestIdle || oldest;
  if (target) {
    console.log(`[Claude] Evicting ${convType} conversation ${target.id.slice(0, 8)} (capacity: ${getConversationCount(convType)}/${maxForType})`);
    abort(target.id);
  }
}

// ── Message processing helpers (used by processOutput) ───────────────────

/**
 * Handle a 'result' message from Claude: send errors and turn_completed.
 * Returns true so the caller can `continue`.
 */
export function handleResultMessage(
  msg: ClaudeMessage,
  state: ConversationState,
  sendWithConvId: SendFn,
): void {
  state.turnActive = false;

  // If the result contains an error, send it as an error message for the chat
  if (msg.is_error || (msg.subtype === 'error_response')) {
    const errorText = typeof msg.result === 'string' ? msg.result
      : typeof msg.error === 'string' ? msg.error
      : '';
    if (errorText) {
      sendWithConvId({ type: 'error', message: errorText });
    }
  }

  // Signal turn_completed with usage stats
  const modelUsageValues = Object.values((msg.modelUsage as Record<string, Record<string, unknown>>) || {});
  sendWithConvId({
    type: 'turn_completed',
    usage: {
      inputTokens: (msg.usage as Record<string, unknown>)?.input_tokens ?? 0,
      outputTokens: (msg.usage as Record<string, unknown>)?.output_tokens ?? 0,
      cacheReadTokens: (msg.usage as Record<string, unknown>)?.cache_read_input_tokens ?? 0,
      totalCost: msg.total_cost_usd ?? 0,
      durationMs: msg.duration_ms ?? 0,
      model: Object.keys((msg.modelUsage as Record<string, unknown>) || {})[0] || '',
      contextWindow: (modelUsageValues[0] as Record<string, unknown>)?.contextWindow ?? 200000,
    },
  });
}

/**
 * Handle an 'assistant' message: compute text delta and forward tool_use blocks.
 * Returns the updated lastSentText for delta tracking.
 */
export function handleAssistantMessage(
  msg: ClaudeMessage,
  lastSentText: string,
  sendWithConvId: SendFn,
): string {
  const message = msg.message as { content?: Array<Record<string, unknown>> };
  const content = message.content;
  if (!Array.isArray(content)) return lastSentText;

  // Extract full text from all text blocks
  const fullText = content
    .filter((b) => b.type === 'text')
    .map((b) => (b.text as string) || '')
    .join('');

  // Compute delta (new text since last emit)
  if (fullText.length > lastSentText.length) {
    const delta = fullText.slice(lastSentText.length);
    lastSentText = fullText;
    sendWithConvId({
      type: 'claude_output',
      data: { type: 'content_block_delta', delta },
    });
  }

  // Forward tool_use blocks as-is (they appear once)
  // Filter out AskUserQuestion — handled via control_request path
  const toolBlocks = content.filter(
    (b) => b.type === 'tool_use' && b.name !== 'AskUserQuestion'
  );
  if (toolBlocks.length > 0) {
    sendWithConvId({
      type: 'claude_output',
      data: { type: 'tool_use', tools: toolBlocks },
    });
  }

  return lastSentText;
}

/**
 * Handle a 'user' (tool_result) message: detect command output or forward as-is.
 * Returns true if a command output was extracted (caller should `continue`).
 */
export function handleUserMessage(
  msg: ClaudeMessage,
  sendWithConvId: SendFn,
): boolean {
  const message = msg.message as { content?: unknown } | undefined;
  if (message && message.content) {
    const raw = typeof message.content === 'string'
      ? message.content
      : Array.isArray(message.content)
        ? (message.content as Array<{ type: string; text?: string }>)
            .filter(b => b.type === 'text')
            .map(b => b.text || '')
            .join('')
        : '';
    const stdoutMatch = raw.match(/<local-command-stdout>([\s\S]*?)<\/local-command-stdout>/);
    const stderrMatch = raw.match(/<local-command-stderr>([\s\S]*?)<\/local-command-stderr>/);
    const cmdOutput = (stdoutMatch && stdoutMatch[1].trim()) || (stderrMatch && stderrMatch[1].trim());
    if (cmdOutput) {
      sendWithConvId({ type: 'command_output', content: cmdOutput });
      return true;
    }
  }

  sendWithConvId({ type: 'claude_output', data: msg });
  return false;
}

async function processOutput(
  child: ChildProcess,
  state: ConversationState,
  stderr: { buf: string },
): Promise<void> {
  const rl = createInterface({ input: child.stdout! });
  const messageStream = new Stream<ClaudeMessage>();

  // Reader: parse JSON lines from stdout → messageStream
  (async () => {
    try {
      for await (const line of rl) {
        if (!line.trim()) continue;
        try {
          const msg: ClaudeMessage = JSON.parse(line);

          // Notify output observers before any processing.
          // If any observer returns true, suppress this message from normal handling.
          let suppressed = false;
          for (const observer of outputObservers) {
            if (observer(state.conversationId, msg)) {
              suppressed = true;
            }
          }
          if (suppressed) {
            continue;
          }

          // Capture session ID from system init
          if (msg.type === 'system' && msg.session_id) {
            state.claudeSessionId = msg.session_id as string;
            state.lastClaudeSessionId = state.claudeSessionId;
            console.log(`[Claude:${state.conversationId.slice(0, 8)}] Session ID: ${state.claudeSessionId}`);
            // Notify web client so sidebar can refresh session list
            sendWithConvId({ type: 'session_started', claudeSessionId: state.claudeSessionId });
          }

          // Handle control_request (tool permission checks)
          if (msg.type === 'control_request') {
            handleControlRequest(msg as unknown as ControlRequest, child, state.conversationId);
            continue;
          }

          // Handle control_cancel_request (abort pending questions)
          if (msg.type === 'control_cancel_request') {
            const reqId = (msg as unknown as { request_id: string }).request_id;
            if (pendingControlRequests.has(reqId)) {
              console.log(`[Claude:${state.conversationId.slice(0, 8)}] Control request cancelled: ${reqId}`);
              pendingControlRequests.delete(reqId);
            }
            continue;
          }

          // Ignore control_response (responses to our own requests, if any)
          if (msg.type === 'control_response') {
            continue;
          }

          messageStream.enqueue(msg);
        } catch {
          // Non-JSON line, ignore
        }
      }
    } catch (err) {
      messageStream.error(err);
    } finally {
      messageStream.done();
      rl.close();
    }
  })();

  // Helper: send message with conversationId
  function sendWithConvId(msg: Record<string, unknown>): void {
    sendFn({ ...msg, conversationId: state.conversationId });
  }

  // Consumer: iterate messages and forward to web client
  let resultHandled = false;
  // Track accumulated text for streaming delta computation
  let lastSentText = '';

  try {
    for await (const msg of messageStream) {
      // ── result → turn complete ──
      if (msg.type === 'result') {
        if (state.turnResultReceived) {
          // Suppress duplicate result (SDK can emit more than one)
          continue;
        }
        state.turnResultReceived = true;
        resultHandled = true;
        lastSentText = '';
        handleResultMessage(msg, state, sendWithConvId);
        continue;
      }

      // ── assistant message → extract delta and forward incrementally ──
      if (msg.type === 'assistant' && msg.message) {
        lastSentText = handleAssistantMessage(msg, lastSentText, sendWithConvId);
        continue;
      }

      // ── user (tool_result) → forward, reset text tracker ──
      if (msg.type === 'user') {
        lastSentText = '';
        if (handleUserMessage(msg, sendWithConvId)) continue;
        continue;
      }

      // ── system messages (init, compact, etc.) ──
      if (msg.type === 'system') {
        const sub = (msg.subtype || '') as string;
        console.log(`[Claude:${state.conversationId.slice(0, 8)}] system/${sub}`);

        // Forward context compaction events to web client
        // New format: subtype='status', status='compacting'
        if (sub === 'status' && msg.status === 'compacting') {
          state.isCompacting = true;
          sendWithConvId({ type: 'context_compaction', status: 'started' });
        }
        // Compact boundary = compaction completed
        else if (sub === 'compact_boundary') {
          state.isCompacting = false;
          sendWithConvId({ type: 'context_compaction', status: 'completed' });
        }
        // Legacy subtypes
        else if (sub === 'compact_start') {
          state.isCompacting = true;
          sendWithConvId({ type: 'context_compaction', status: 'started' });
        } else if (sub === 'compact_complete' || sub === 'compact_end') {
          state.isCompacting = false;
          sendWithConvId({ type: 'context_compaction', status: 'completed' });
        }
        continue;
      }
    }
  } catch (err) {
    const error = err as Error;
    if (error.name === 'AbortError') {
      console.log(`[Claude:${state.conversationId.slice(0, 8)}] Query aborted`);
    } else if (resultHandled) {
      // Ignore post-turn errors
      console.warn(`[Claude:${state.conversationId.slice(0, 8)}] Ignoring post-result error: ${error.message}`);
    } else {
      console.error(`[Claude:${state.conversationId.slice(0, 8)}] Error: ${error.message}`);
      sendWithConvId({
        type: 'error',
        message: `Claude error: ${error.message}`,
      });
    }
  } finally {
    // If the process exited mid-turn without a result, notify web client with error
    if (!resultHandled && state.turnActive) {
      if (stderr.buf.trim()) {
        sendWithConvId({ type: 'error', message: stderr.buf.trim() });
      }
      sendWithConvId({ type: 'turn_completed' });
    }
    state.turnActive = false;

    // Notify close observers (used by team + scheduler modules)
    for (const observer of closeObservers) {
      observer(state.conversationId, child.exitCode, resultHandled);
    }

    // Only clean up if this conversation is still in the map with the same state
    if (conversations.get(state.conversationId) === state) {
      state.child = null;
      state.inputStream = null;
    }
  }
}

/**
 * Handle an incoming control_request from Claude's stdout.
 * For AskUserQuestion: forward to web UI and wait for user answer.
 * For other tools: auto-approve immediately.
 */
function handleControlRequest(request: ControlRequest, child: ChildProcess, conversationId: string): void {
  const requestId = request.request_id;
  const subtype = request.request?.subtype;

  if (subtype === 'can_use_tool' && request.request.tool_name === 'AskUserQuestion') {
    console.log(`[Claude:${conversationId.slice(0, 8)}] AskUserQuestion control_request: ${requestId}`);
    pendingControlRequests.set(requestId, { request, child, conversationId });

    // Forward to web UI
    sendFn({
      type: 'ask_user_question',
      conversationId,
      requestId,
      questions: (request.request.input as Record<string, unknown>)?.questions || [],
    });
    return;
  }

  // Auto-approve all other tool calls
  const response = buildControlResponse(requestId, request.request.input || {});

  if (child.stdin && !child.stdin.destroyed) {
    child.stdin.write(JSON.stringify(response) + '\n');
  }
}

/**
 * Clean up a specific conversation: kill process, clear pending requests, remove from map.
 */
function cleanupConversation(conversationId: string): void {
  const conv = conversations.get(conversationId);
  if (!conv) return;

  // Clear pending control requests belonging to this conversation
  for (const [reqId, pending] of pendingControlRequests) {
    if (pending.conversationId === conversationId) {
      pendingControlRequests.delete(reqId);
    }
  }

  conv.isCompacting = false;

  // Preserve session ID so the next message can resume
  if (conv.claudeSessionId) {
    conv.lastClaudeSessionId = conv.claudeSessionId;
  }

  if (conv.child && !conv.child.killed) {
    const pid = conv.child.pid;
    // On Windows, kill the entire process tree (child.kill() won't kill grandchildren)
    if (pid && process.platform === 'win32') {
      try {
        execSync(`taskkill /pid ${pid} /t /f`, { stdio: 'ignore', windowsHide: true });
      } catch { /* process may have already exited */ }
    } else {
      conv.child.kill();
    }
  }
  if (conv.inputStream) {
    conv.inputStream.done();
  }

  conversations.delete(conversationId);
}
