/**
 * Claude Code SDK integration.
 *
 * Spawns `claude` as a child process with --output-format stream-json
 * and --input-format stream-json for persistent bidirectional communication.
 *
 * Supports multiple concurrent conversations, each with its own Claude process.
 * Conversations are keyed by conversationId (a UUID generated by the web client).
 * When no conversationId is provided (backward compat), uses 'default' as the key.
 *
 * Lifecycle:
 *   1.  Web user sends first message → startQuery() spawns Claude process
 *   2.  Each user message is enqueued into the inputStream
 *   3.  processOutput() iterates Claude stdout, forwarding messages via sendFn
 *   4.  On 'result' message → turn is complete, process stays alive for next turn
 *   5.  On abort / process exit → cleanup
 */

import { spawn, execSync, type ChildProcess } from 'child_process';
import { createInterface } from 'readline';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { Stream } from './stream.js';
import {
  resolveClaudeCommand,
  getCleanEnv,
  streamToStdin,
} from './sdk.js';
import { CONFIG_DIR } from './config.js';

// ── Types ──────────────────────────────────────────────────────────────────

export interface ClaudeMessage {
  type: string;
  subtype?: string;
  [key: string]: unknown;
}

export interface ChatFile {
  name: string;
  mimeType: string;
  data: string; // base64
}

export interface ConversationState {
  child: ChildProcess | null;
  inputStream: Stream<ClaudeMessage> | null;
  abortController: AbortController | null;
  claudeSessionId: string | null;
  workDir: string;
  turnActive: boolean;
  turnResultReceived: boolean;
  // Multi-session fields
  conversationId: string;
  lastClaudeSessionId: string | null;
  isCompacting: boolean;
  createdAt: number;
}

type SendFn = (msg: Record<string, unknown>) => void;

// ── Control request types ──────────────────────────────────────────────────

interface ControlRequest {
  type: 'control_request';
  request_id: string;
  request: {
    subtype: string;
    tool_name?: string;
    input?: Record<string, unknown>;
  };
}

interface PendingControlRequest {
  request: ControlRequest;
  child: ChildProcess;
  conversationId: string;
}

// ── Constants ─────────────────────────────────────────────────────────────

const DEFAULT_CONVERSATION_ID = 'default';
export const MAX_CONVERSATIONS = 5;

// ── Module state ───────────────────────────────────────────────────────────

const conversations = new Map<string, ConversationState>();
let sendFn: SendFn = () => {};
const pendingControlRequests = new Map<string, PendingControlRequest>();

export function setSendFn(fn: SendFn): void {
  sendFn = fn;
}

/**
 * Get a conversation by its conversationId.
 * If no conversationId is provided, returns the 'default' conversation (backward compat).
 */
export function getConversation(conversationId?: string): ConversationState | null {
  return conversations.get(conversationId || DEFAULT_CONVERSATION_ID) || null;
}

/** Get all active conversations. */
export function getConversations(): Map<string, ConversationState> {
  return conversations;
}

/**
 * Evict any idle conversation that holds the given claudeSessionId.
 * Returns true if a busy (turnActive) conversation blocked the eviction.
 */
export function evictByClaudeSessionId(claudeSessionId: string): boolean {
  for (const [convId, conv] of conversations) {
    if (conv.claudeSessionId === claudeSessionId || conv.lastClaudeSessionId === claudeSessionId) {
      if (conv.turnActive) return true; // busy — caller should block
      cleanupConversation(convId);
    }
  }
  return false;
}

/**
 * Rebind a running conversation to a new conversationId.
 * Finds the conversation by claudeSessionId and remaps its key in the Map.
 * Used when the web client reconnects (page refresh) with a new conversationId.
 */
export function rebindConversation(claudeSessionId: string, newConvId: string): boolean {
  for (const [oldConvId, conv] of conversations) {
    if ((conv.claudeSessionId === claudeSessionId || conv.lastClaudeSessionId === claudeSessionId)
        && oldConvId !== newConvId) {
      conversations.delete(oldConvId);
      conv.conversationId = newConvId;
      conversations.set(newConvId, conv);
      // Update pending control requests that reference the old conversationId
      for (const pending of pendingControlRequests.values()) {
        if (pending.conversationId === oldConvId) {
          pending.conversationId = newConvId;
        }
      }
      console.log(`[Claude] Rebound conversation ${oldConvId.slice(0, 8)} → ${newConvId.slice(0, 8)} (session ${claudeSessionId.slice(0, 8)})`);
      return true;
    }
  }
  return false;
}

/** Whether context compaction is currently in progress for a conversation. */
export function getIsCompacting(conversationId?: string): boolean {
  const conv = conversations.get(conversationId || DEFAULT_CONVERSATION_ID);
  return conv?.isCompacting ?? false;
}

/**
 * Clear the saved session ID for a conversation.
 * If no conversationId is provided, clears all (backward compat).
 */
export function clearSessionId(conversationId?: string): void {
  if (conversationId) {
    const conv = conversations.get(conversationId);
    if (conv) {
      conv.lastClaudeSessionId = null;
    }
  } else {
    for (const conv of conversations.values()) {
      conv.lastClaudeSessionId = null;
    }
  }
}

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Handle a chat message from the web client.
 * Lazily starts the Claude process on the first message.
 * If resumeSessionId is provided, resumes that Claude session.
 */
export function handleChat(
  conversationId: string | undefined,
  prompt: string,
  workDir: string,
  resumeSessionId?: string,
  files?: ChatFile[],
): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const existing = conversations.get(convId);

  if (!existing || !existing.inputStream) {
    // If the process exited but we still know the session ID, resume it
    const sessionToResume = resumeSessionId || existing?.claudeSessionId || existing?.lastClaudeSessionId || undefined;
    startQuery(convId, workDir, sessionToResume);
  }

  const state = conversations.get(convId)!;
  state.turnActive = true;
  state.turnResultReceived = false;

  console.log(`[Claude:${convId.slice(0, 8)}] Sending: ${prompt.substring(0, 100)}${prompt.length > 100 ? '...' : ''}`);

  if (files && files.length > 0) {
    const content = processFilesForClaude(files, workDir, prompt);
    state.inputStream!.enqueue({
      type: 'user',
      message: { role: 'user', content },
    });
  } else {
    state.inputStream!.enqueue({
      type: 'user',
      message: { role: 'user', content: prompt },
    });
  }
}

/**
 * Abort a specific conversation's Claude process.
 * If no conversationId, aborts the 'default' conversation (backward compat).
 */
export function abort(conversationId?: string): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  if (!conv) return;

  if (conv.abortController) {
    conv.abortController.abort();
  }
  cleanupConversation(convId);
}

/**
 * Abort all conversations (used on agent shutdown).
 */
export function abortAll(): void {
  for (const convId of [...conversations.keys()]) {
    abort(convId);
  }
}

/**
 * Cancel the current execution for a conversation (user pressed stop button).
 * Kills the process and notifies the web client.
 */
export function cancelExecution(conversationId?: string): void {
  const convId = conversationId || DEFAULT_CONVERSATION_ID;
  const conv = conversations.get(convId);
  if (!conv) return;

  console.log(`[Claude:${convId.slice(0, 8)}] Cancelling execution`);
  conv.turnActive = false;

  if (conv.abortController) {
    conv.abortController.abort();
  }
  cleanupConversation(convId);

  sendFn({ type: 'execution_cancelled', conversationId: convId });
}

/**
 * Handle the user's answer to an AskUserQuestion control request.
 * Writes a control_response back to Claude's stdin.
 */
export function handleUserAnswer(requestId: string, answers: Record<string, unknown>): void {
  const pending = pendingControlRequests.get(requestId);
  if (!pending) {
    console.warn(`[Claude] No pending control request for requestId: ${requestId}`);
    return;
  }

  pendingControlRequests.delete(requestId);
  console.log(`[Claude] Answering AskUserQuestion ${requestId}`);

  const controlResponse = {
    type: 'control_response',
    response: {
      subtype: 'success',
      request_id: pending.request.request_id,
      response: {
        behavior: 'allow',
        updatedInput: {
          questions: pending.request.request.input?.questions || [],
          answers,
        },
      },
    },
  };

  if (pending.child.stdin && !pending.child.stdin.destroyed) {
    pending.child.stdin.write(JSON.stringify(controlResponse) + '\n');
  }
}

// ── Internal ───────────────────────────────────────────────────────────────

function processFilesForClaude(files: ChatFile[], workDir: string, prompt: string): unknown[] {
  const attachDir = join(CONFIG_DIR, 'tmp-attachments');
  if (!existsSync(attachDir)) {
    mkdirSync(attachDir, { recursive: true });
  }

  const content: unknown[] = [];
  const nonImagePaths: string[] = [];

  for (const file of files) {
    const timestamp = Date.now();
    const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_');
    const diskName = `${timestamp}-${safeName}`;
    const diskPath = join(attachDir, diskName);

    // Write file to disk
    writeFileSync(diskPath, Buffer.from(file.data, 'base64'));
    console.log(`[Claude] Saved attachment: ${diskPath}`);

    if (file.mimeType.startsWith('image/')) {
      // Images: send as inline base64 content blocks
      content.push({
        type: 'image',
        source: {
          type: 'base64',
          media_type: file.mimeType,
          data: file.data,
        },
      });
    } else {
      // Non-images: reference by file path
      nonImagePaths.push(diskPath);
    }
  }

  // Build text block with prompt + file references
  let textContent = prompt;
  if (nonImagePaths.length > 0) {
    textContent += '\n\nAttached files:\n' + nonImagePaths.map(p => `- ${p}`).join('\n');
  }
  content.push({ type: 'text', text: textContent });

  return content;
}

function startQuery(conversationId: string, workDir: string, resumeSessionId?: string): void {
  // Tear down previous process for THIS conversation only (not others)
  const existing = conversations.get(conversationId);
  if (existing) {
    abort(conversationId);
  }

  // Evict oldest idle conversation if at capacity
  if (conversations.size >= MAX_CONVERSATIONS) {
    evictOldestIdle(conversationId);
  }

  const inputStream = new Stream<ClaudeMessage>();
  const abortController = new AbortController();

  const state: ConversationState = {
    child: null,
    inputStream,
    abortController,
    claudeSessionId: resumeSessionId || null,
    workDir,
    turnActive: false,
    turnResultReceived: false,
    conversationId,
    lastClaudeSessionId: existing?.lastClaudeSessionId || null,
    isCompacting: false,
    createdAt: Date.now(),
  };

  conversations.set(conversationId, state);

  // Build args
  // bypassPermissions auto-approves all regular tool calls.
  // --permission-prompt-tool stdio tells Claude CLI to send control_request
  // via stdout for interactive tools (like AskUserQuestion) instead of
  // auto-denying them. Our handleControlRequest() intercepts these and
  // either auto-approves or forwards to the web UI.
  const args = [
    '--output-format', 'stream-json',
    '--input-format', 'stream-json',
    '--verbose',
    '--permission-mode', 'bypassPermissions',
    '--permission-prompt-tool', 'stdio',
  ];

  if (resumeSessionId) {
    args.push('--resume', resumeSessionId);
    console.log(`[Claude:${conversationId.slice(0, 8)}] Resuming session: ${resumeSessionId}`);
  }

  const { command, prefixArgs, spawnOpts } = resolveClaudeCommand();
  const env = getCleanEnv();

  console.log(`[Claude:${conversationId.slice(0, 8)}] Spawning: ${command} ${[...prefixArgs, ...args].join(' ')}`);
  console.log(`[Claude:${conversationId.slice(0, 8)}] cwd: ${workDir}`);

  const child = spawn(command, [...prefixArgs, ...args], {
    cwd: workDir,
    stdio: ['pipe', 'pipe', 'pipe'],
    signal: abortController.signal,
    env,
    ...spawnOpts,
    windowsHide: true, // must come after spread to prevent override
  });

  state.child = child;

  // Pipe user messages → stdin
  streamToStdin(inputStream, child.stdin, abortController.signal);

  // Capture stderr for debugging (use object so processOutput sees updates)
  const stderr = { buf: '' };
  child.stderr.on('data', (data: Buffer) => {
    const text = data.toString();
    stderr.buf += text;
    if (process.env.DEBUG) console.error('[Claude stderr]', text);
  });

  // Process stdout (JSON lines)
  processOutput(child, state, stderr);

  // Handle process exit
  child.on('close', (code) => {
    if (code !== 0 && code !== null && !abortController.signal.aborted) {
      const msg = stderr.buf
        ? `Claude process exited with code ${code}: ${stderr.buf.trim()}`
        : `Claude process exited with code ${code}`;
      console.error(`[Claude:${conversationId.slice(0, 8)}] ${msg}`);
    }
  });

  child.on('error', (err) => {
    if (!abortController.signal.aborted) {
      console.error(`[Claude:${conversationId.slice(0, 8)}] Process error: ${err.message}`);
    }
  });
}

/**
 * Evict the oldest idle conversation to make room for a new one.
 * Only evicts conversations that are NOT actively processing (turnActive === false).
 * If all conversations are active, evicts the oldest one regardless.
 */
function evictOldestIdle(excludeId: string): void {
  let oldest: { id: string; createdAt: number } | null = null;
  let oldestIdle: { id: string; createdAt: number } | null = null;

  for (const [id, conv] of conversations) {
    if (id === excludeId) continue;

    if (!oldest || conv.createdAt < oldest.createdAt) {
      oldest = { id, createdAt: conv.createdAt };
    }
    if (!conv.turnActive && (!oldestIdle || conv.createdAt < oldestIdle.createdAt)) {
      oldestIdle = { id, createdAt: conv.createdAt };
    }
  }

  const target = oldestIdle || oldest;
  if (target) {
    console.log(`[Claude] Evicting conversation ${target.id.slice(0, 8)} (capacity: ${conversations.size}/${MAX_CONVERSATIONS})`);
    abort(target.id);
  }
}

async function processOutput(
  child: ChildProcess,
  state: ConversationState,
  stderr: { buf: string },
): Promise<void> {
  const rl = createInterface({ input: child.stdout! });
  const messageStream = new Stream<ClaudeMessage>();

  // Reader: parse JSON lines from stdout → messageStream
  (async () => {
    try {
      for await (const line of rl) {
        if (!line.trim()) continue;
        try {
          const msg: ClaudeMessage = JSON.parse(line);

          // Capture session ID from system init
          if (msg.type === 'system' && msg.session_id) {
            state.claudeSessionId = msg.session_id as string;
            state.lastClaudeSessionId = state.claudeSessionId;
            console.log(`[Claude:${state.conversationId.slice(0, 8)}] Session ID: ${state.claudeSessionId}`);
            // Notify web client so sidebar can refresh session list
            sendWithConvId({ type: 'session_started', claudeSessionId: state.claudeSessionId });
          }

          // Handle control_request (tool permission checks)
          if (msg.type === 'control_request') {
            handleControlRequest(msg as unknown as ControlRequest, child, state.conversationId);
            continue;
          }

          // Handle control_cancel_request (abort pending questions)
          if (msg.type === 'control_cancel_request') {
            const reqId = (msg as unknown as { request_id: string }).request_id;
            if (pendingControlRequests.has(reqId)) {
              console.log(`[Claude:${state.conversationId.slice(0, 8)}] Control request cancelled: ${reqId}`);
              pendingControlRequests.delete(reqId);
            }
            continue;
          }

          // Ignore control_response (responses to our own requests, if any)
          if (msg.type === 'control_response') {
            continue;
          }

          messageStream.enqueue(msg);
        } catch {
          // Non-JSON line, ignore
        }
      }
    } catch (err) {
      messageStream.error(err);
    } finally {
      messageStream.done();
      rl.close();
    }
  })();

  // Helper: send message with conversationId
  function sendWithConvId(msg: Record<string, unknown>): void {
    sendFn({ ...msg, conversationId: state.conversationId });
  }

  // Consumer: iterate messages and forward to web client
  let resultHandled = false;
  // Track accumulated text for streaming delta computation
  let lastSentText = '';

  try {
    for await (const msg of messageStream) {
      // ── result → turn complete ──
      if (msg.type === 'result') {
        if (state.turnResultReceived) {
          // Suppress duplicate result (SDK can emit more than one)
          continue;
        }
        state.turnResultReceived = true;
        resultHandled = true;
        state.turnActive = false;

        // Reset streaming text tracker
        lastSentText = '';

        // If the result contains an error, send it as an error message for the chat
        if (msg.is_error || (msg.subtype === 'error_response')) {
          const errorText = typeof msg.result === 'string' ? msg.result
            : typeof msg.error === 'string' ? msg.error
            : '';
          if (errorText) {
            sendWithConvId({ type: 'error', message: errorText });
          }
        }

        // Forward the result, then signal turn_completed
        sendWithConvId({ type: 'claude_output', data: msg });
        sendWithConvId({ type: 'turn_completed' });
        continue;
      }

      // ── assistant message → extract delta and forward incrementally ──
      if (msg.type === 'assistant' && msg.message) {
        const message = msg.message as { content?: Array<Record<string, unknown>> };
        const content = message.content;
        if (Array.isArray(content)) {
          // Extract full text from all text blocks
          const fullText = content
            .filter((b) => b.type === 'text')
            .map((b) => (b.text as string) || '')
            .join('');

          // Compute delta (new text since last emit)
          if (fullText.length > lastSentText.length) {
            const delta = fullText.slice(lastSentText.length);
            lastSentText = fullText;
            sendWithConvId({
              type: 'claude_output',
              data: { type: 'content_block_delta', delta },
            });
          }

          // Forward tool_use blocks as-is (they appear once)
          // Filter out AskUserQuestion — handled via control_request path
          const toolBlocks = content.filter(
            (b) => b.type === 'tool_use' && b.name !== 'AskUserQuestion'
          );
          if (toolBlocks.length > 0) {
            sendWithConvId({
              type: 'claude_output',
              data: { type: 'tool_use', tools: toolBlocks },
            });
          }
        }
        continue;
      }

      // ── user (tool_result) → forward, reset text tracker ──
      if (msg.type === 'user') {
        // New turn segment — reset delta tracker for next assistant message
        lastSentText = '';

        // Check for command output (e.g. /cost, /context) — extract and send separately
        const message = msg.message as { content?: unknown } | undefined;
        if (message && message.content) {
          const raw = typeof message.content === 'string'
            ? message.content
            : Array.isArray(message.content)
              ? (message.content as Array<{ type: string; text?: string }>)
                  .filter(b => b.type === 'text')
                  .map(b => b.text || '')
                  .join('')
              : '';
          const stdoutMatch = raw.match(/<local-command-stdout>([\s\S]*?)<\/local-command-stdout>/);
          const stderrMatch = raw.match(/<local-command-stderr>([\s\S]*?)<\/local-command-stderr>/);
          const cmdOutput = (stdoutMatch && stdoutMatch[1].trim()) || (stderrMatch && stderrMatch[1].trim());
          if (cmdOutput) {
            sendWithConvId({ type: 'command_output', content: cmdOutput });
            continue;
          }
        }

        sendWithConvId({ type: 'claude_output', data: msg });
        continue;
      }

      // ── system messages (init, compact, etc.) ──
      if (msg.type === 'system') {
        const sub = (msg.subtype || '') as string;
        console.log(`[Claude:${state.conversationId.slice(0, 8)}] system/${sub}`);

        // Forward context compaction events to web client
        // New format: subtype='status', status='compacting'
        if (sub === 'status' && msg.status === 'compacting') {
          state.isCompacting = true;
          sendWithConvId({ type: 'context_compaction', status: 'started' });
        }
        // Compact boundary = compaction completed
        else if (sub === 'compact_boundary') {
          state.isCompacting = false;
          sendWithConvId({ type: 'context_compaction', status: 'completed' });
        }
        // Legacy subtypes
        else if (sub === 'compact_start') {
          state.isCompacting = true;
          sendWithConvId({ type: 'context_compaction', status: 'started' });
        } else if (sub === 'compact_complete' || sub === 'compact_end') {
          state.isCompacting = false;
          sendWithConvId({ type: 'context_compaction', status: 'completed' });
        }
        continue;
      }
    }
  } catch (err) {
    const error = err as Error;
    if (error.name === 'AbortError') {
      console.log(`[Claude:${state.conversationId.slice(0, 8)}] Query aborted`);
    } else if (resultHandled) {
      // Ignore post-turn errors
      console.warn(`[Claude:${state.conversationId.slice(0, 8)}] Ignoring post-result error: ${error.message}`);
    } else {
      console.error(`[Claude:${state.conversationId.slice(0, 8)}] Error: ${error.message}`);
      sendWithConvId({
        type: 'error',
        message: `Claude error: ${error.message}`,
      });
    }
  } finally {
    // If the process exited mid-turn without a result, notify web client with error
    if (!resultHandled && state.turnActive) {
      if (stderr.buf.trim()) {
        sendWithConvId({ type: 'error', message: stderr.buf.trim() });
      }
      sendWithConvId({ type: 'turn_completed' });
    }
    state.turnActive = false;

    // Only clean up if this conversation is still in the map with the same state
    if (conversations.get(state.conversationId) === state) {
      state.child = null;
      state.inputStream = null;
    }
  }
}

/**
 * Handle an incoming control_request from Claude's stdout.
 * For AskUserQuestion: forward to web UI and wait for user answer.
 * For other tools: auto-approve immediately.
 */
function handleControlRequest(request: ControlRequest, child: ChildProcess, conversationId: string): void {
  const requestId = request.request_id;
  const subtype = request.request?.subtype;

  if (subtype === 'can_use_tool' && request.request.tool_name === 'AskUserQuestion') {
    console.log(`[Claude:${conversationId.slice(0, 8)}] AskUserQuestion control_request: ${requestId}`);
    pendingControlRequests.set(requestId, { request, child, conversationId });

    // Forward to web UI
    sendFn({
      type: 'ask_user_question',
      conversationId,
      requestId,
      questions: (request.request.input as Record<string, unknown>)?.questions || [],
    });
    return;
  }

  // Auto-approve all other tool calls
  const autoApproveResponse = {
    type: 'control_response',
    response: {
      subtype: 'success',
      request_id: requestId,
      response: {
        behavior: 'allow',
        updatedInput: request.request.input || {},
      },
    },
  };

  if (child.stdin && !child.stdin.destroyed) {
    child.stdin.write(JSON.stringify(autoApproveResponse) + '\n');
  }
}

/**
 * Clean up a specific conversation: kill process, clear pending requests, remove from map.
 */
function cleanupConversation(conversationId: string): void {
  const conv = conversations.get(conversationId);
  if (!conv) return;

  // Clear pending control requests belonging to this conversation
  for (const [reqId, pending] of pendingControlRequests) {
    if (pending.conversationId === conversationId) {
      pendingControlRequests.delete(reqId);
    }
  }

  conv.isCompacting = false;

  // Preserve session ID so the next message can resume
  if (conv.claudeSessionId) {
    conv.lastClaudeSessionId = conv.claudeSessionId;
  }

  if (conv.child && !conv.child.killed) {
    const pid = conv.child.pid;
    // On Windows, kill the entire process tree (child.kill() won't kill grandchildren)
    if (pid && process.platform === 'win32') {
      try {
        execSync(`taskkill /pid ${pid} /t /f`, { stdio: 'ignore', windowsHide: true });
      } catch { /* process may have already exited */ }
    } else {
      conv.child.kill();
    }
  }
  if (conv.inputStream) {
    conv.inputStream.done();
  }

  conversations.delete(conversationId);
}
